Update patch set 8
Patch Set 8: Code-Review-1

Needs release notes and documentation.
Could not find anything in the docs relating to authentication,
Which seems to be required.
I put a nexus block in my .config/lftools/lftools.ini
with my lfid but still was unable to authenticate.
And example would be nice as well, as have not used nexus
so I did not know what to put on the command line.

(I realize these search parameters do not return anything.)
$ lftools nexus docker list '*' opendaylight.release --server http://nexus.opendaylight.org
ERROR: http://nexus.opendaylight.org/service/local/search?q=*&repository=opendaylight.release returned <Response [403]>

Patch-set: 8
Label: Code-Review=-1