Update patch set 3
Patch Set 3:

Modified it a bit, and now the output looks like this

$ lftools nexus release --verify-only --server https://nexus.opendaylight.org odlparent-2132
Failed to get nexus credentials; using empty username and password.
Request URL: https://nexus.opendaylight.org/service/local/staging/repository/odlparent-2132/activity
One or more rules failed
javadoc-staging --> Missing: no javadoc jar found in folder '/org/opendaylight/odlparent/leveldbjni-all/6.0.1'
com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed

Patch-set: 3